### ISSUE TITLE
Highlight search terms in the results

### ISSUE THREAD

**Issue by RoneoOrg** [zwbetz-gh/hugo-client-side-search-template#1]
Hi there,

to make results easier to scan, search terms could be highlighted, like in these examples:

- based on Fuse.js : https://hbs.razonyang.com/v1/en/search/?q=hugo
- based on Fuse too: https://codingnconcepts.com/hugo/client-side-search-engine-hugo/
- handmade code + Mark.js: https://decovar.dev/blog/2020/01/05/hugo-search/
- https://demo.stack.jimmycai.com/search/?keyword=hugo

Thanks for sharing this repo!

**Comment by zwbetz-gh** [comment]
Normally I only fixes bugs, and don't do "nice to haves". But I like this idea.

Done in https://github.com/zwbetz-gh/hugo-client-side-search-template/commit/30652915e1aeec5bf39699ba6682255510714e82.

Now substring matches will be highlighted. 

Sample screenshot:

<img width="710" alt="Screen Shot 2022-09-25 at 10 42 30 PM" src="https://user-images.githubusercontent.com/37317628/192189710-0fad19f0-0353-465b-af24-4b35a249d46b.png">

**Comment by RoneoOrg** [comment]
Awesome, thank you!
