### ISSUE TITLE
Decouple stats from code

### ISSUE THREAD

**Issue by bwc69151** [zwbetz-gh/hugo-client-side-search-template#10]
I came across this repo from the Hugo Forum. Now, I would like to decouple all stats based code because it throws errors in the console when I remove the stats import code at the top. I tried removing a few lines but the search breaks. Where do you recommend I start? I saw not all parts of the code are commented.

**Comment by zwbetz-gh** [comment]
Remove the following lines:

1. https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/67af96298fbf5557f237ab409b1f195c837c6777/assets/js/main.ts#L1-L4
2. https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/67af96298fbf5557f237ab409b1f195c837c6777/assets/js/main.ts#L49
3. https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/67af96298fbf5557f237ab409b1f195c837c6777/assets/js/main.ts#L71-L72
4. https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/67af96298fbf5557f237ab409b1f195c837c6777/assets/js/main.ts#L80-L81
5. https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/67af96298fbf5557f237ab409b1f195c837c6777/assets/js/main.ts#L163-L164

**Comment by bwc69151** [comment]
Thanks! All errors gone now. They were also appearing on [pagespeed insights](ttps://pagespeed.web.dev/).
