### ISSUE TITLE
Searching the post content | Request

### ISSUE THREAD

**Issue by LinguistFM** [zwbetz-gh/hugo-client-side-search-template#12]
Thank you sir for making this amazingly clean theme opensource.

I've tried to make the content searchable and have put some text in the .md files 

I've added to index.json.json:

`"content" .Plain` and `"content" (.Content | plainify)` 

But it doesn't seem to work form me.
Is it possible that you help me do it ?

Thank you again for sharing, for your time, and for your support.

`{{- $list := slice -}}

{{- range site.RegularPages.ByPublishDate.Reverse -}}
  {{- $item := dict
  "title" .Title
  "content" .Plain
  "country" .Params.country
  "crew" .Params.crew
  "vehicle" .Params.vehicle
  "param_date" .Params.param_date
  "duration" .Params.duration
  "purpose" .Params.purpose
  "url" .RelPermalink -}}

  {{- $list = $list | append $item -}}
{{- end -}}

{{- $list | jsonify -}}`

**Comment by zwbetz-gh** [comment]
If you post a link to a github repo that minimally reproduces your issue, I can look into it.

**Comment by zwbetz-gh** [comment]
This repo is working fine locally. I'm able to search as normal. Tested with hugo v0.107.0

**Comment by zwbetz-gh** [comment]
You can see the search work on the demo as well: https://hugo-client-side-search-template.netlify.app/?query=astro
