### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by dryscord** [zwbetz-gh/hugo-client-side-search-template#13]
Hi. This was asked here before. I found replacing
 ```
JSON_INDEX_URL = `${window.location.origin}/index.json`;
```
 with the code below works for a site with two languages. Perhaps you can mention it somewhere in the readme?
```
let JSON_INDEX_URL;

if (document.querySelector('html[lang="<!-- put the default language code as defined in your config file --> "]')) {
  JSON_INDEX_URL = `${window.location.origin}/index.json`;
} else {
  // Define an alternative URL or fallback value. Replace `fr` with the language path of your index.json for secondary language
  JSON_INDEX_URL = `${window.location.origin}/fr/index.json`;
}
```

**Comment by zwbetz-gh** [comment]
Hi @dryscord - feel free to share/link your solution on this issue https://github.com/zwbetz-gh/hugo-client-side-search-template/issues/2

I'll think about if/how to show this in the readme

**Comment by zwbetz-gh** [comment]
Linked your issue in the readme 👍 

https://github.com/zwbetz-gh/hugo-client-side-search-template/commit/9c3b3cd8a386b9d8f799e2f5b874fecd42745d65
