### ISSUE TITLE
ERROR deprecated: .Site.IsServer

### ISSUE THREAD

**Issue by ka259** [zwbetz-gh/hugo-client-side-search-template#18]
https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/main/layouts/partials/scripts.html
```
ERROR deprecated: .Site.IsServer was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.139.0. Use hugo.IsServer instead.
```
Also in `baseof.html`

**Comment by zwbetz-gh** [comment]
Fixed by https://github.com/zwbetz-gh/hugo-client-side-search-template/commit/df3a53a080bd26a9ebdb2552cb6ae95016741dec

**Comment by zwbetz-gh** [comment]
Thanks for opening this btw.
