### ISSUE TITLE
Error when exporting fuse JS

### ISSUE THREAD

**Issue by ka259** [zwbetz-gh/hugo-client-side-search-template#19]
Error with current fuse JS https://cdn.jsdelivr.net/npm/fuse.js/dist/fuse.js `import Fuse from './fuse.mjs';`

```
ERROR JSBUILD: failed to transform "/js/main.ts" (text/typescript): "...main.ts:1:7": No matching export in "js/fuse.mjs" for import "default"
```

**Comment by zwbetz-gh** [comment]
The latest Fuse version is [v7.0.0](https://github.com/krisk/Fuse/releases/tag/v7.0.0) which is what this project uses, see:

https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/4368362c7502d28a57edc55a3573d22f12703d3c/assets/js/fuse.mjs#L2

Note that when you download and unzip the Fuse assets and look in the `dist` dir, you must choose the correct file, which is `fuse.mjs`

```
fuse.basic.cjs
fuse.basic.js
fuse.basic.min.cjs
fuse.basic.min.js
fuse.basic.min.mjs
fuse.basic.mjs
fuse.cjs
fuse.d.ts
fuse.js
fuse.min.cjs
fuse.min.js
fuse.min.mjs
fuse.mjs
```

**Comment by ka259** [comment]
Your version works. But the one from the Fuse CDN does not, and it also reads version 7.0.0. Just run it in your project and see the error in action.

**Comment by zwbetz-gh** [comment]
This is because you're picking `fuse.js` from the cdn, but you need to pick `fuse.mjs` - note the **ext** difference.

Here is the correct cdn link for this project: https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.mjs

You can also view **[all](https://cdn.jsdelivr.net/npm/fuse.js/dist/)** cdn dist files.

**Comment by ka259** [comment]
Ooh. MJS vs JS. noted

**Comment by zwbetz-gh** [comment]
Updated the readme for future users https://github.com/zwbetz-gh/hugo-client-side-search-template/commit/80b9a70e72047241669197c10324c7fa9ab3dd55
