### ISSUE TITLE
Avoid inline CSS

### ISSUE THREAD

**Issue by jafaican** [zwbetz-gh/hugo-client-side-search-template#3]
How about replacing the `style="background-color: #fff3cd;"` with a CSS class instead? The code threw errors in my server due to Content Security Policy.

**Comment by zwbetz-gh** [comment]
I'm going to keep the code as-is.

But, in your case, if you need external CSS instead of inline CSS, you can make a new class, like:

```css
.match {
  background-color: #fff3cd;
}
```

Then make sure that CSS file is linked in the relevant search page.
