### ISSUE TITLE
Show summary conditionally

### ISSUE THREAD

**Issue by jafaican** [zwbetz-gh/hugo-client-side-search-template#4]
I want to do something like `{{ with .Params.summary }}{{ "Summary" (.Content | plainify) }}{{ end }}` for one field in the JSON file. But since your code uses 'dict', I am unsure of how to do that. Do you have any idea how to achieve it?

**Comment by zwbetz-gh** [comment]
This is more of a help request, and less of an issue.

I don't understand your example. `{{ with .Params.summary }}` will change the context of the "dot", so `{{ "Summary" (.Content | plainify) }}` would not work.

With all of that said, I can give you an example of adding a `summary` key to the JSON index...

Tweak this file: https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/main/layouts/index.json.json

To be:

```
{{- $list := slice -}}

{{- range site.RegularPages.ByPublishDate.Reverse -}}
  {{- $item := dict
  "title" .Title
  "summary" (trim (.Summary | plainify | htmlUnescape) "\n\r " | default "")
  "country" .Params.country
  "crew" .Params.crew
  "vehicle" .Params.vehicle
  "param_date" .Params.param_date
  "duration" .Params.duration
  "purpose" .Params.purpose
  "url" .RelPermalink -}}

  {{- $list = $list | append $item -}}
{{- end -}}

{{- $list | jsonify -}}
```

Only this line was added:

```
"summary" (trim (.Summary | plainify | htmlUnescape) "\n\r " | default "")
```

**Comment by jafaican** [comment]
Perhaps a discussion section for help requests would suffice? What I am trying to do is no show the summary field in search where posts don't have a summary. So, that field and the label are ommited all together on those posts.
