### ISSUE TITLE
Clear search option

### ISSUE THREAD

**Issue by jafaican** [zwbetz-gh/hugo-client-side-search-template#5]
Is it possible to introduce an option to clear the search box of whatever is typed in there?

**Comment by zwbetz-gh** [comment]
This is more of a help request, and less of an issue.

Yes, it's possible.

You could have a button, that when clicked, clears the input value...

```ts
// in the click handler ...
getInputEl().value = '';
```

**Comment by jafaican** [comment]
> This is more of a help request

It is a feature request.

**Comment by broughtupsy** [comment]
ChatGPT can help. I already got this to work.
