### ISSUE TITLE
Searching by number and result doesn't show

### ISSUE THREAD

**Issue by bapps2** [zwbetz-gh/hugo-client-side-search-template#7]
Based on #6 , same dataset, I have a Title with a number in it, "12 engineers".
1. Typing `12` nothing shows up.  https://prnt.sc/A4hb4IqvCj5B
2. But adding a letter it shows up https://prnt.sc/ursa6QTVEQQO

**Comment by zwbetz-gh** [comment]
Try changing this to a lower number:

https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/67af96298fbf5557f237ab409b1f195c837c6777/assets/js/main.ts#L30

**Comment by bapps2** [comment]
Awesome!

**Comment by zwbetz-gh** [comment]
FYI, `FUSE_OPTIONS` can contain any of the following options. Tweak it to your needs. 

https://fusejs.io/api/options.html
