### ISSUE TITLE
What are these meant to do?

### ISSUE THREAD

**Issue by bapps2** [zwbetz-gh/hugo-client-side-search-template#8]
https://github.com/zwbetz-gh/hugo-client-side-search-template#assetsjstypests

**Comment by zwbetz-gh** [comment]
The TypeScript `Page` interface in `assets/js/types.ts` must match the keys defined in the Hugo JSON index at `layouts/index.json.json`

**Comment by bapps2** [comment]
I have not defined them and I don't see any effect on my search results.

**Comment by zwbetz-gh** [comment]
I can only help you if you provide a minimal, reproducible example.
Preferably as a git repo.

Remember, this is an issue queue, not an area to request general help.

**Comment by bapps2** [comment]
I just needed more clarification on that.
